### Registrar usuario
POST http://localhost:3000/register HTTP/1.1
content-type: application/json

{
  "username": "andresruiu",
  "password": "testpassword"
}

### Iniciar sesión
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
  "username": "andresruiu",
  "password": "testpassword"
}

### Info solo para usuarios autenticados
GET http://localhost:3000/info HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHJlc3J1aXUiLCJpYXQiOjE3MTgzMzEwMTcsImV4cCI6MTcxODMzNDYxN30.VaMpJm7sVqQlcBOfN52_rR6KssjhbT83og11QVMuwlQ

### Cerrar sesión
GET http://localhost:3000/logout HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZHJlc3J1aXUiLCJpYXQiOjE3MTgzMzEwMTcsImV4cCI6MTcxODMzNDYxN30.VaMpJm7sVqQlcBOfN52_rR6KssjhbT83og11QVMuwlQ
